### ISSUE TITLE
Sintesis_AnaLaura

### ISSUE THREAD

**Issue by Anna-Aparicio** [SistemasTecTlaxiaco/sintesis-Anna-Aparicio#2]
[SINTESIS_ANALAURA.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-Anna-Aparicio/files/7156758/SINTESIS_ANALAURA.pdf)

**Comment by EDITH-R** [comment]
Calificación:20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
